name: Build

on:
    push:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    pull_request_target:
        branches:
            - "*"
        paths-ignore:
            - ".gitignore"
    workflow_dispatch:
permissions: write-all
jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build and test"
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}

            -   uses: ./.github/actions/setup-normal-workspace
            -   name: Build with Gradle
                run: ./gradlew assemble -x test --stacktrace
            -   uses: actions/upload-artifact@v4
                name: Upload development build
                with:
                    name: "Development Build"
                    path: build/libs/*.jar
            -   name: Test with Gradle
                run: ./gradlew test
            -   uses: actions/upload-artifact@v4
                name: "Upload test report"
                if: ${{ !cancelled() }}
                with:
                    name: "Test Results"
                    path: versions/1.8.9/build/reports/tests/test/

    preprocess:
        runs-on: ubuntu-latest
        name: "Build multi version"
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.ref }}
                    repository: ${{ github.event.pull_request.head.repo.full_name }}

            -   uses: ./.github/actions/setup-normal-workspace
            -   name: Enable preprocessor
                run: |
                    mkdir -p .gradle
                    echo skyhanni.multi-version=compile > .gradle/private.properties
            -   name: Build with Gradle
                run: ./gradlew build --stacktrace -PskipDetekt=true

            -   name: Add label if build fails
                if: ${{ failure() && github.event_name == 'pull_request' && github.event.pull_request.state == 'open' }}
                uses: actions-ecosystem/action-add-labels@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    labels: 'Fails Multi-Version'

            -   name: Remove label if build passes
                if: ${{ success() && github.event_name == 'pull_request' && github.event.pull_request.state == 'open' }}
                uses: actions-ecosystem/action-remove-labels@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    labels: 'Fails Multi-Version'

            -   name: Upload multi-version build
                uses: actions/upload-artifact@v4
                if: ${{ !cancelled() }}
                with:
                    name: "Multi-version Development Build"
                    path: build/libs/*.jar
