name: Check PR Dependencies

on:
    pull_request_target:
        types: [ opened, edited, synchronize, closed ]

permissions:
    contents: read
    pull-requests: write

jobs:
    check-dependencies:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repository
                uses: actions/checkout@v4

            -   name: Evaluate dependency PRs
                uses: actions/github-script@v7
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        const check = require('./.github/scripts/check-dependencies.js');
                        await check({ github, context, core });
